[project]
name = "semana1-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "egonzalezauh", email = "198632528+egonzalezauh@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
